apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft_services
spec:
  ports:
  - port: 2000
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: ft_services
    tier: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: ft_services
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 22
          hostPort: 2000
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: login
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: login
              key: password
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssh-config
          mountPath: /etc/ssh/sshd_config
          subPath: sshd_config
        - name: tls-key
          mountPath: etc/nginx/tls.crt
          subPath: tls.crt
        - name: tls-key
          mountPath: etc/nginx/tls.key
          subPath: tls.key
        - name: ssh-key
          mountPath: /etc/ssh/ssh_host_rsa_key
          subPath: ssh_host_rsa_key
      restartPolicy: Always
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: ssh-config
        configMap:
          name: ssh-config
      - name: tls-key
        secret:
          secretName: tls-key
      - name: ssh-key
        secret:
          defaultMode: 0400
          secretName: ssh-key